/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'
import { Route as ReviewSlugRouteImport } from './routes/review.$slug'
import { Route as GoSlugRouteImport } from './routes/go.$slug'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'
import { Route as ApiPublicAutomationPostsScheduleRouteImport } from './routes/api/public/automation/posts.schedule'
import { Route as ApiPublicAutomationPostsImportRouteImport } from './routes/api/public/automation/posts.import'
import { Route as ApiPublicAutomationMetadataGenerateRouteImport } from './routes/api/public/automation/metadata.generate'
import { Route as ApiPublicAutomationImagesImportRouteImport } from './routes/api/public/automation/images.import'
import { Route as ApiPublicAutomationCategoriesAssignRouteImport } from './routes/api/public/automation/categories.assign'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToolsRoute,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReviewsRoute,
} as any)
const ReviewSlugRoute = ReviewSlugRouteImport.update({
  id: '/review/$slug',
  path: '/review/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompareRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicAutomationPostsScheduleRoute =
  ApiPublicAutomationPostsScheduleRouteImport.update({
    id: '/api/public/automation/posts/schedule',
    path: '/api/public/automation/posts/schedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationPostsImportRoute =
  ApiPublicAutomationPostsImportRouteImport.update({
    id: '/api/public/automation/posts/import',
    path: '/api/public/automation/posts/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationMetadataGenerateRoute =
  ApiPublicAutomationMetadataGenerateRouteImport.update({
    id: '/api/public/automation/metadata/generate',
    path: '/api/public/automation/metadata/generate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationImagesImportRoute =
  ApiPublicAutomationImagesImportRouteImport.update({
    id: '/api/public/automation/images/import',
    path: '/api/public/automation/images/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationCategoriesAssignRoute =
  ApiPublicAutomationCategoriesAssignRouteImport.update({
    id: '/api/public/automation/categories/assign',
    path: '/api/public/automation/categories/assign',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/api/public/automation/categories/assign': typeof ApiPublicAutomationCategoriesAssignRoute
  '/api/public/automation/images/import': typeof ApiPublicAutomationImagesImportRoute
  '/api/public/automation/metadata/generate': typeof ApiPublicAutomationMetadataGenerateRoute
  '/api/public/automation/posts/import': typeof ApiPublicAutomationPostsImportRoute
  '/api/public/automation/posts/schedule': typeof ApiPublicAutomationPostsScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/api/public/automation/categories/assign': typeof ApiPublicAutomationCategoriesAssignRoute
  '/api/public/automation/images/import': typeof ApiPublicAutomationImagesImportRoute
  '/api/public/automation/metadata/generate': typeof ApiPublicAutomationMetadataGenerateRoute
  '/api/public/automation/posts/import': typeof ApiPublicAutomationPostsImportRoute
  '/api/public/automation/posts/schedule': typeof ApiPublicAutomationPostsScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/api/public/automation/categories/assign': typeof ApiPublicAutomationCategoriesAssignRoute
  '/api/public/automation/images/import': typeof ApiPublicAutomationImagesImportRoute
  '/api/public/automation/metadata/generate': typeof ApiPublicAutomationMetadataGenerateRoute
  '/api/public/automation/posts/import': typeof ApiPublicAutomationPostsImportRoute
  '/api/public/automation/posts/schedule': typeof ApiPublicAutomationPostsScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/disclosure'
    | '/login'
    | '/privacy'
    | '/reviews'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/compare/$slug'
    | '/go/$slug'
    | '/review/$slug'
    | '/reviews/$slug'
    | '/tools/$slug'
    | '/admin/'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/api/public/health'
    | '/admin/posts/'
    | '/admin/products/'
    | '/api/public/automation/categories/assign'
    | '/api/public/automation/images/import'
    | '/api/public/automation/metadata/generate'
    | '/api/public/automation/posts/import'
    | '/api/public/automation/posts/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/disclosure'
    | '/login'
    | '/privacy'
    | '/reviews'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/compare/$slug'
    | '/go/$slug'
    | '/review/$slug'
    | '/reviews/$slug'
    | '/tools/$slug'
    | '/admin'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/api/public/health'
    | '/admin/posts'
    | '/admin/products'
    | '/api/public/automation/categories/assign'
    | '/api/public/automation/images/import'
    | '/api/public/automation/metadata/generate'
    | '/api/public/automation/posts/import'
    | '/api/public/automation/posts/schedule'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/disclosure'
    | '/login'
    | '/privacy'
    | '/reviews'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/compare/$slug'
    | '/go/$slug'
    | '/review/$slug'
    | '/reviews/$slug'
    | '/tools/$slug'
    | '/admin/'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/api/public/health'
    | '/admin/posts/'
    | '/admin/products/'
    | '/api/public/automation/categories/assign'
    | '/api/public/automation/images/import'
    | '/api/public/automation/metadata/generate'
    | '/api/public/automation/posts/import'
    | '/api/public/automation/posts/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CompareRoute: typeof CompareRouteWithChildren
  ContactRoute: typeof ContactRoute
  DisclosureRoute: typeof DisclosureRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  GoSlugRoute: typeof GoSlugRoute
  ReviewSlugRoute: typeof ReviewSlugRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicAutomationCategoriesAssignRoute: typeof ApiPublicAutomationCategoriesAssignRoute
  ApiPublicAutomationImagesImportRoute: typeof ApiPublicAutomationImagesImportRoute
  ApiPublicAutomationMetadataGenerateRoute: typeof ApiPublicAutomationMetadataGenerateRoute
  ApiPublicAutomationPostsImportRoute: typeof ApiPublicAutomationPostsImportRoute
  ApiPublicAutomationPostsScheduleRoute: typeof ApiPublicAutomationPostsScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/review/$slug': {
      id: '/review/$slug'
      path: '/review/$slug'
      fullPath: '/review/$slug'
      preLoaderRoute: typeof ReviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof CompareRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/automation/posts/schedule': {
      id: '/api/public/automation/posts/schedule'
      path: '/api/public/automation/posts/schedule'
      fullPath: '/api/public/automation/posts/schedule'
      preLoaderRoute: typeof ApiPublicAutomationPostsScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/posts/import': {
      id: '/api/public/automation/posts/import'
      path: '/api/public/automation/posts/import'
      fullPath: '/api/public/automation/posts/import'
      preLoaderRoute: typeof ApiPublicAutomationPostsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/metadata/generate': {
      id: '/api/public/automation/metadata/generate'
      path: '/api/public/automation/metadata/generate'
      fullPath: '/api/public/automation/metadata/generate'
      preLoaderRoute: typeof ApiPublicAutomationMetadataGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/images/import': {
      id: '/api/public/automation/images/import'
      path: '/api/public/automation/images/import'
      fullPath: '/api/public/automation/images/import'
      preLoaderRoute: typeof ApiPublicAutomationImagesImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/categories/assign': {
      id: '/api/public/automation/categories/assign'
      path: '/api/public/automation/categories/assign'
      fullPath: '/api/public/automation/categories/assign'
      preLoaderRoute: typeof ApiPublicAutomationCategoriesAssignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CompareRouteChildren {
  CompareSlugRoute: typeof CompareSlugRoute
}

const CompareRouteChildren: CompareRouteChildren = {
  CompareSlugRoute: CompareSlugRoute,
}

const CompareRouteWithChildren =
  CompareRoute._addFileChildren(CompareRouteChildren)

interface ReviewsRouteChildren {
  ReviewsSlugRoute: typeof ReviewsSlugRoute
}

const ReviewsRouteChildren: ReviewsRouteChildren = {
  ReviewsSlugRoute: ReviewsSlugRoute,
}

const ReviewsRouteWithChildren =
  ReviewsRoute._addFileChildren(ReviewsRouteChildren)

interface ToolsRouteChildren {
  ToolsSlugRoute: typeof ToolsSlugRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsSlugRoute: ToolsSlugRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CompareRoute: CompareRouteWithChildren,
  ContactRoute: ContactRoute,
  DisclosureRoute: DisclosureRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  CategoriesSlugRoute: CategoriesSlugRoute,
  GoSlugRoute: GoSlugRoute,
  ReviewSlugRoute: ReviewSlugRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicAutomationCategoriesAssignRoute:
    ApiPublicAutomationCategoriesAssignRoute,
  ApiPublicAutomationImagesImportRoute: ApiPublicAutomationImagesImportRoute,
  ApiPublicAutomationMetadataGenerateRoute:
    ApiPublicAutomationMetadataGenerateRoute,
  ApiPublicAutomationPostsImportRoute: ApiPublicAutomationPostsImportRoute,
  ApiPublicAutomationPostsScheduleRoute: ApiPublicAutomationPostsScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
